--- 
- name: Basic System Setup
  hosts: localhost
  become: true
  vars: 
    ansible_python_interpreter: /usr/libexec/platform-python
  tasks:
    - name: Update all security-related packages
      ansible.builtin.package:
        name: '*'
        state: latest
        security: true

    - name: Create a new user
      ansible.builtin.package:
        name: 'test'
        state: present
        create_home: true
