- name: Test sudo limited
  hosts: localhost
  gather_facts: false
  connection: ssh
  become: true
  become_user: root
  tasks:
    - command: /usr/bin/systemctl is-active sshd
    - command: whoami
